server:
  port: 8081

spring:
  application:
    name: uaiou

  datasource:
    url: jdbc:postgresql://localhost:32768/uaiou
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

token:
  access:
    duration: 3600
